# -*- coding: utf-8 -*-
"""TASK - 2(2) (Program to print all positive numbers in a range).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15VfGvIVZbMiHykXtUBwly_7xvf5wkRJT
"""

list1 = [12, -7, 5, 64, -14]
#execution/condition
for number in list1:
  if number > 0:
    print (number)

list2 = [12, 14, -95, 3]
#execution/condition
for number in list2:
  if number > 0:
    print(number)

list2 = [7, -5, -2, 3, 0, -45, 45]
#execution/condition
for number in list2:
  if number > 0:
    print(number)