# -*- coding: utf-8 -*-
"""TASK - 3 (Program to Illustrate Different Set Operations).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1okHZx3dlLQloT5IdZnPTLmGGuWCUZ-Af

E-N = 8,0,6  E,N = 0,1,2,3,4,5,6,8, E&N = 2,4

SO, E= 80624 N=12345
"""

E = {0, 2, 4, 6, 8};
N = {1, 2, 3, 4, 5};

print("Union of E and N is",E | N)

print("Intersection of E and N is",E & N)

print("Difference of E and N is",E - N)

print("Symmetric difference of E and N is",E ^ N)