# -*- coding: utf-8 -*-
"""Task - 1(Print 'Hello World!'.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B54NY58hQfRYPQbjqCxLvHuRpCfjKFoK
"""

#Displaying Hello World!
a="Hello World!"
print(a)